# 服务端口
server:
  port: 8201
  # 服务名
spring:
  application.name: service-hosp
  # 环境设置：dev、test、prod
  profiles.active: dev

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #rabbitmq地址
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#  #设置sentinel地址
#    sentinel:
#      transport:
#        dashboard: http://127.0.0.1:8858
#
  #mongodb地址
  data:
    mongodb:
      host: localhost
      port: 27017
      database: yygh_hosp
  #配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#
#  #开启sentinel
#feign:
#  sentinel:
#    enabled: true

#logging:
#  level:
#    root: DEBUG