# 服务端口
server:
  port: 8207
  # 服务名
spring:
  application:
    name: service-task
  # 环境设置：dev、test、prod
  profiles:
    active: dev

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #rabbitmq地址
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
