# 服务端口
server:
  port: 8204
  # 服务名
spring:
  application:
    name: service-msm

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
  #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

aliyun:
  sms:
    regionId: default
    accessKeyId: xxx
    secret: xxx
