# 服务端口
server:
  port: 8206
  # 服务名
spring:
  application:
    name: service-order
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  data:
    mongodb:
      uri: mongodb://localhost:27017/yygh_hosp
  
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  
  #rabbitmq地址
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        # 最大阻塞等待时间
        max-idle: 5
        min-idle: 0

weixin:
  # 公众号appid
  appid: xxx
  # 商户号
  partner: xxx
  # 商户key
  partnerkey: xxx
  # 证书
  cert: xxx//xxx
