# 服务端口
server:
  port: 80
  # 服务名
spring:
  application:
    name: service-gateway
  
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  
  #使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
  #设置路由id
      routes[0]:
        id: service-hosp
  #设置路由的uri
        uri: lb://service-hosp
  #设置路由断言,代理servicerId为auth-service的/auth/路径
        predicates:  Path=/*/hosp/**
  
  #设置路由id
      routes[1]:
        id: service-cmn
  #设置路由的uri
        uri: lb://service-cmn
  #设置路由断言,代理servicerId为auth-service的/auth/路径
        predicates: Path=/*/cmn/**

  #设置路由id
      routes[2]:
        id: service-user
  #设置路由的uri
        uri: lb://service-user
  #设置路由断言,代理servicerId为auth-service的/auth/路径
        predicates: Path=/*/user/**

  #设置路由id
      routes[3]:
        id: service-msm
  #设置路由的uri
        uri: lb://service-msm
  #设置路由断言,代理servicerId为auth-service的/auth/路径
        predicates:  Path=/*/msm/**

      #设置路由id
      routes[4]:
        id: service-user
        #设置路由的uri
        uri: lb://service-user
        #设置路由断言,代理servicerId为auth-service的/auth/路径
        predicates:  Path=/*/ucenter/**

      #设置路由id
      routes[5]:
        id: service-oss
        #设置路由的uri
        uri: lb://service-oss
        #设置路由断言,代理servicerId为auth-service的/auth/路径
        predicates:  Path=/*/oss/**

      #设置路由id
      routes[6]:
        id: service-order
        #设置路由的uri
        uri: lb://service-order
        #设置路由断言,代理servicerId为auth-service的/auth/路径
        predicates:  Path=/*/order/**

      #设置路由id
      routes[7]:
        id: service-statistics
        #设置路由的uri
        uri: lb://service-statistics
        #设置路由断言,代理servicerId为auth-service的/auth/路径
        predicates:  Path=/*/statistics/**